services:
  - type: web
    name: email-scraper
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn email_scraper.web_app:app"
    envVars:
      - key: SERPAPI_KEY
        value: your_serpapi_key_here
      - key: SECRET_KEY
        generateValue: true
    autoDeploy: true